spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/phiyun?useSSL=false&serverTimezone=UTC
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop